# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  imagename: 'test'
  registryname: 'imagedestination1.azurecr.io'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Image Destination Registry'
    repository: '$(imagename)'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Image Destination Registry'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Aqua ACR Login'
    command: 'login'

- task: aquasecScanner@4
  inputs:
    image: '$(registryname)/$(imagename):$(Build.BuildId)'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'aquascanner.azurecr.io/aquasec/scanner:latest'
    runOptions: '--privileged'
    connection: 'Aqua Scanner Info'
    caCertificates: true
    scanMalware: true

- task: Docker@2
  inputs:
    containerRegistry: 'Image Destination Registry'
    repository: '$(imagename)'
    command: 'push'

