# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  imagename: 'test'
  registryname: 'mylabtestacr.azurecr.io'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'TESTACR5'
    repository: '$(imagename)'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Aqua Lab ACR Login'
    command: 'login'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $AQUA_SCANNER_NAME
      docker pull stsaquaseclab.azurecr.io/aquasec/scanner:5.3.21119
    
- task: aquasecScanner@4
  inputs:
    image: '$(registryname)/$(imagename):$(Build.BuildId)'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'stsaquaseclab.azurecr.io/aquasec/scanner:5.3.21119'
    runOptions: '--privileged -e SCALOCK_LOG_LEVEL=DEBUG'
    registry: 'mylabtestacr'
    connection: 'Aqua Lab Scanner Info'
    customFlags: '--direct-cc'
    caCertificates: true
    scanMalware: true
    registerCompliant: true

- task: Docker@2
  inputs:
    containerRegistry: 'TESTACR5'
    repository: '$(imagename)'
    command: 'push'

