# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  imageName: 'atmdestnacr.azurecr.io/test'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DestnACRLogin'
    repository: $(imagename)
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: $(Build.BuildId)


- task: Docker@2
  inputs:
    containerRegistry: 'DestnACRLogin'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'SourceACRLogin'
    command: 'login'

- task: aquasecScanner@4
  inputs:
    image: '$(imageName):$(Build.BuildId)'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'atmsourceacr.azurecr.io/aquasec/scanner:latest'
    runOptions: '--privileged'
    connection: 'AquaScanner'
    caCertificates: true
    scanMalware: true

- task: Docker@2
  inputs:
    containerRegistry: 'DestnACRLogin'
    repository: 'test'
    command: 'push'
    tags: $(Build.BuildId)