# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Windows-2019'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker pull mcr.microsoft.com/dotnet/core/aspnet
      docker tag mcr.microsoft.com/dotnet/core/aspnet:latest aspnet:latest

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'scanner.exe scan -H https://aquasec-nonprod.ey.com/ -U aqua-nonprod-scanner -P Sc@n3r99 --local asp:latest'
    errorActionPreference: 'continue'