# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Windows-2019'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Aqua NProd Login'
    command: 'login'


- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker pull mcr.microsoft.com/dotnet/core/aspnet
      docker tag mcr.microsoft.com/dotnet/core/aspnet:latest aspnet:latest
      docker pull acemnldaquacr01.azurecr.io/aquasec/scanner:latest
    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'docker run  --rm -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/tmp acemnldaquacr01.azurecr.io/aquasec/scanner:latest scan --user aqua-nonprod-scanner --password Sc@n3r99 --host https://aquasec-nonprod.ey.com/ --local asp:latest --jsonfile /tmp/out.json --htmlfile /tmp/out.html > C:\Information Security\AquasecCICD\Logs'