# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DestnACRLogin'
    repository: 'test'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'latest'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo $(Build.Repository.Name)
      echo $(Build.BuildId)

- task: Docker@2
  inputs:
    containerRegistry: 'DestnACRLogin'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'SourceACRLogin'
    command: 'login'

- task: aquasecScanner@4
  inputs:
    image: 'test:latest'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: 'atmsourceacr.azurecr.io/aquasec/scanner:latest'
    runOptions: '--privileged'
    connection: 'AquaScanner'
    caCertificates: true

- task: Docker@2
  inputs:
    containerRegistry: 'DestnACRLogin'
    repository: 'test'
    command: 'push'
    tags: 'latest'