# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  imagename: 'imagedestination1.azurecr.io/test'

steps:
- task: Docker@2
  inputs:
    repository: '$(imagename)'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- task: Docker@2
  inputs:
    containerRegistry: 'Image Destination Registry'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'Image Destination Registry'
    repository: '$(imagename)'
    command: 'push'

