# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


variables:
  imagename: 'atmdestnacr.azurecr.io/test'

steps:
- task: Docker@2
  inputs:
    #containerRegistry: 'DestnACRLogin'
    repository: $(imagename)
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: $(Build.BuildId)


- task: Docker@2
  inputs:
    containerRegistry: 'DestnACRLogin'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'SourceACRLogin'
    command: 'login'

- task: aquasecScanner@4
  inputs:
    image: '$(imagename):$(Build.BuildId)'
    scanType: 'local'
    register: false
    hideBase: false
    showNegligible: false
    windowsScannerVersion: '4.2.0'
    scanner: '$(AQUA_SCANNER_NAME)'
    runOptions: '--privileged'
    registry: 'atmdestnacr.azurecr.io'
    connection: 'AquaScanner'
    caCertificates: true
    scanMalware: true
    
- task: Docker@2
  inputs:
    containerRegistry: 'DestnACRLogin'
    repository: $(imagename)
    command: 'push'
    tags: $(Build.BuildId)